spring:
  application:
    name: retenx
  config:
    import: optional:file:.env[.properties]

retenx:
  version: v@project.version@
  keycloak:
    realm: ${KC_REALM}
    auth-server-url: ${KC_AUTH_SERVER_URL}
    client-id: ${KC_CLIENT_ID}
    client-secret: ${KC_CLIENT_SECRET}
    admin:
      username: ${KC_ADMIN_USERNAME}
      password: ${KC_ADMIN_PASSWORD}