spring:
  application:
    name: Retenx
  profiles:
    active: dev
  threads:
    virtual:
      enabled: true
  config:
    import: optional:file:.env[.properties]
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KC_AUTH_SERVER_URL}/realms/${KC_REALM}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

retenx:
  version: v@project.version@
  keycloak:
    realm: ${KC_REALM}
    auth-server-url: ${KC_AUTH_SERVER_URL}
    client-id: ${KC_CLIENT_ID}
    client-secret: ${KC_CLIENT_SECRET}
    admin:
      username: ${KC_ADMIN_USERNAME}
      password: ${KC_ADMIN_PASSWORD}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:*}